# Numpy
### Basic and powerful package for working with data(n-dimentional array)
### Numpy use for: Financial Function, Linear Algebra, Statistics, Polynomials, Sorting, Searching etc.

In [1]:
import numpy as np 

In [2]:
# create nd array from list
l = [1,2,3,4,5]
np_arr = np.array(l)
np_arr

array([1, 2, 3, 4, 5])

In [3]:
type(np_arr)

numpy.ndarray

In [4]:
# efficiency check
import sys

s = range(1000)
d = np.array(1000)
sys.getsizeof(5)*len(s), 'bytes'

(28000, 'bytes')

In [5]:
d.itemsize, 'bytes'

(4, 'bytes')

In [6]:
import time

SIZE = 1000000
l1 = l2 = range(SIZE)
a1 = a2 = np.arange(SIZE)
start = time.time()

r = [(x+y) for x, y in zip(l1, l2)]
stop = time.time()
print('Time taken by Python:', (stop - start)*1000, 'ms')

start = time.time()
r = a1 + a2
stop = time.time()
print('Time taken by Numpy:', (stop - start)*1000, 'ms')

Time taken by Python: 97.57637977600098 ms
Time taken by Numpy: 8.000373840332031 ms


In [7]:
# 1-Dimentional array
a = np.array([1,2,6])
a

array([1, 2, 6])

In [8]:
# 2-Dimentional array
b = np.array([[7,8,9], [10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# dimention of array
b.ndim

2

In [10]:
# show row-columns in data
b.shape    

(2, 3)

In [11]:
# reshape
b.reshape(3, 2)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [12]:
# flatten use for linear dim
b.flatten()

array([ 7,  8,  9, 10, 11, 12])

In [13]:
# 3-Dimentional array
c = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
c.ndim

3

In [15]:
# horizontal-stacking & vertical-stacking
f = np.array([1,6,8])
g = np.array([7,0,4])
print("H-stack:", np.hstack((f, g)))
print("V-stack:\n", np.vstack((f, g)))

H-stack: [1 6 8 7 0 4]
V-stack:
 [[1 6 8]
 [7 0 4]]


In [16]:
# slicing
k = np.array([[5,2,6], [8,4,0]])
print(k[:,1],"\n",k[1,:],"\n",k[::-1])

[2 4] 
 [8 4 0] 
 [[8 4 0]
 [5 2 6]]


In [17]:
k = k.astype('float')
k[1, 1]= np.nan
k

array([[ 5.,  2.,  6.],
       [ 8., nan,  0.]])

In [18]:
k[1, 2]= np.inf
k

array([[ 5.,  2.,  6.],
       [ 8., nan, inf]])

In [19]:
m = [[0,1,2], [3,4,5]]
arr = np.array(m, dtype='float')
print(arr)
print(arr.astype('int'))
arr.tolist()

[[0. 1. 2.]
 [3. 4. 5.]]
[[0 1 2]
 [3 4 5]]


[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]]

In [20]:
n = [[1,2,3,4], [5,6,7,8], [11,12,13,14]]
ar = np.array(n, dtype='float')
ar

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [11., 12., 13., 14.]])

In [21]:
print("Mean of ar:", ar.mean())
print("Max Value of ar:", ar.max())
print("Min Value of ar:", ar.min())

Mean of ar: 7.166666666666667
Max Value of ar: 14.0
Min Value of ar: 1.0


In [22]:
print('Column wise min of ar:', np.amin(ar, axis=0))
print('Row wise min of ar:', np.amin(ar, axis=1))

Column wise min of ar: [1. 2. 3. 4.]
Row wise min of ar: [ 1.  5. 11.]


In [23]:
x = np.array([[3,4], [5,6]], dtype='float')
y = np.array([[7,8], [9,10]], dtype=np.float64)

print("Addition:", np.add(x, y))
print("subtraction:", np.subtract(x, y))
print("Multiplication:", np.multiply(x, y))
print("Division:", np.divide(x, y))
print(np.sqrt(x))

Addition: [[10. 12.]
 [14. 16.]]
subtraction: [[-4. -4.]
 [-4. -4.]]
Multiplication: [[21. 32.]
 [45. 60.]]
Division: [[0.42857143 0.5       ]
 [0.55555556 0.6       ]]
[[1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [24]:
# create array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# create array of zeros
np.zeros((2,3,4), dtype=np.int16)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [26]:
# create array with random values
np.random.random((2,2))

array([[0.77163477, 0.74778404],
       [0.69891411, 0.6900331 ]])

In [27]:
# create an empty array
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
# create full array
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [29]:
# create an array of evenly-spaced values
np.arange(10, 25, 5)

array([10, 15, 20])

In [30]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])